application/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from core.views import Main_page, RegisterFormView
from django.contrib.auth.views import LoginView
from django.conf import settings
from django.contrib.auth.views import logout


urlpatterns = [

    url(r'^register/$', RegisterFormView.as_view()),
    url(r'^login/$', LoginView.as_view(template_name = 'core/login.html'),name = 'login'),
    url(r'^logout/$', logout, {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),
    url(r'^$', Main_page.as_view(),name = 'main'),
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blogs')),
    url(r'^post/', include('post.urls', namespace='posts')),
    url(r'^category/', include('category.urls', namespace='categories')),
]

blog/urls.py
from django.conf.urls import url
from blog.views import *

urlpatterns = [

    url(r'^$', Blog_list.as_view(), name="blogview"),
    url(r'^(?P<pk>\d+)/$', blog_page, name="currentblog"),

]

category/urls.py
from django.conf.urls import url
from .views import *


urlpatterns = [

    url(r'^$', Category_list.as_view(), name="category_list"),
    url(r'^(?P<pk>\d+)/$', Category_page, name="current_category"),

]

post/urls.py
from django.conf.urls import url
from .views import *

from django.contrib.auth.decorators import login_required


urlpatterns = [

    url(r'^(?P<pk>\d+)/$',Post_page.as_view(), name="currentpost"),
    url(r'^new/$',login_required(New_Post.as_view()), name="post_creation"),
    url(r'^(?P<pk>\d+)/edit/$',login_required(Post_Update.as_view()), name="post_update"),
]

category/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.conf import settings


class Category(models.Model):

    title = models.CharField(max_length=255)
    def __unicode__(self):
        return self.title

# Create your models here.

category/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
from .models import Category
from django.views.generic import ListView
from django import forms



class Category_List_Form(forms.Form):

    order_by = forms.ChoiceField(choices = (
        ('title','Title asc'),
        ('-title', 'Title desc'),
        ('id','ID'),
    ),required = False)
    search = forms.CharField(required = False)

class Category_list(ListView):

    model = Category
    context_object_name = 'categories'
    template_name = "category/category_list.html"
    paginate_by = 5

    def get_queryset(self):
        q = super(Category_list, self).get_queryset()
        self.form = Category_List_Form(self.request.GET)
        if self.form.is_valid():

            if self.form.cleaned_data['order_by']:
                q = q.order_by(self.form.cleaned_data['order_by'])
            if self.form.cleaned_data['search']:
                q = q.filter(title=self.form.cleaned_data['search'])
        return q

    def get_context_data(self, **kwargs):
        context = super(Category_list, self).get_context_data(**kwargs)
        context['searchform'] = self.form
        return context



def Category_page (request, pk=None):
    category = Category.objects.get(pk=pk)
    return render (request, 'category/category_page.html', {'category': category}, )

category/templates/category/category_list.html
{% extends "core/base.html" %}

{% block title %}
<h1>Список категорий</h1>
{% endblock %}

{% block menu %}

{% endblock %}

{% block content %}
 <form action="" method="get">
  {{ searchform }}

  <input type="submit" value="Search">
 </form>

{% for category in categories%}
 <h1>
   <a href="{% url "categories:current_category" pk=category.pk %}">{{ category.title }}</a>
   ({{category.posts.count}} posts)
 </h1>
{% endfor %}

{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}




{% endblock %}

category/templates/category/category_page.html
{% extends "core/base.html" %}

{% block title %}

<h1>{{category.title}}</h1>

{% endblock %}

{% block menu %}

{% endblock %}

{% block content %}

{% for post in category.posts.all%}

   <div><a href="{% url "posts:currentpost" pk=post.pk %}">{{ post.title }}</a></div>

    {% endfor %}



{% endblock %}