application/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from core.views import Main_page, RegisterFormView
from django.contrib.auth.views import LoginView
from django.conf import settings
from django.contrib.auth.views import logout


urlpatterns = [

    url(r'^register/$', RegisterFormView.as_view()),
    url(r'^login/$', LoginView.as_view(template_name = 'core/login.html'),name = 'login'),
    url(r'^logout/$', logout, {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),
    url(r'^$', Main_page.as_view(),name = 'main'),
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blogs')),
    url(r'^post/', include('post.urls', namespace='posts')),
    url(r'^category/', include('category.urls', namespace='categories')),
]

blog/urls.py
from django.conf.urls import url
from blog.views import *

urlpatterns = [

    url(r'^$', Blog_list.as_view(), name="blogview"),
    url(r'^(?P<pk>\d+)/$', blog_page, name="currentblog"),

]

category/urls.py
from django.conf.urls import url
from .views import *


urlpatterns = [

    url(r'^$', Category_list.as_view(), name="category_list"),
    url(r'^(?P<pk>\d+)/$', Category_page, name="current_category"),

]

post/urls.py
from django.conf.urls import url
from .views import *

from django.contrib.auth.decorators import login_required


urlpatterns = [

    url(r'^(?P<pk>\d+)/$',Post_page.as_view(), name="currentpost"),
    url(r'^new/$',login_required(New_Post.as_view()), name="post_creation"),
    url(r'^(?P<pk>\d+)/edit/$',login_required(Post_Update.as_view()), name="post_update"),
]

post/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.conf import settings
from category.models import Category


class Post(models.Model):

    author = models.ForeignKey(settings.AUTH_USER_MODEL)
    title = models.CharField(max_length=255,verbose_name=u'Title')
    text = models.TextField()
    blog = models.ForeignKey('blog.Blog',related_name='posts')
    categories = models.ManyToManyField(Category,related_name='posts')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_deleted = models.BooleanField(default=False)

    def __unicode__(self):
        return self.title




# Create your models here.

post/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render,reverse,redirect
from .models import Post
from comment.models import Comment
from django.views.generic import CreateView,UpdateView

class Post_Update(UpdateView):

   template_name = 'post/edit_post.html'
   model = Post
   fields = 'title', 'text'

   def get_queryset(self):
      return super(Post_Update, self).get_queryset().filter(author = self.request.user)
   def get_success_url(self):
      return reverse('posts:currentpost',kwargs={'pk': self.object.pk})



class New_Post(CreateView):

   template_name = 'post/new_post.html'
   model = Post
   fields = 'title', 'text'

   def get_success_url(self):
      return reverse('posts:currentpost',kwargs={'pk': self.object.pk})

   def form_valid(self,form):
      form.instance.author = self.request.user
      form.instance.blog_id = self.request.user.id
      return super(New_Post, self).form_valid(form)


class Post_page(CreateView):

    template_name = "post/post_page.html"
    model = Comment
    fields = ('text',)


    def get_context_data(self, **kwargs):
        context = super(Post_page, self).get_context_data(**kwargs)
        context['post'] = Post.objects.get(pk=self.kwargs.get('pk'))
        return context

    def get_success_url(self):
        #return redirect(self.request.META['HTTP_REFERER'])
       return reverse('posts:currentpost',pk=self.kwargs.get('pk'))


    def form_valid(self, form):
       form.instance.author = self.request.user
       form.instance.post_id = self.kwargs.get('pk')
       return super(Post_page, self).form_valid(form)




# Create your views here.

post/templates/post/edit_post.html
{% extends "core/base.html" %}

{% block title %}
<h1>Редактирование поста</h1>
{% endblock %}

{% block menu %}

{% endblock %}

{% block content %}
 <form action="" method="post">
     {{ form }}
     {% csrf_token %}
     <input type="submit" value="Update">
 </form>

{% endblock %}

post/templates/post/new_post.html
{% extends "core/base.html" %}

{% block title %}
<h1>Создание нового поста</h1>
{% endblock %}

{% block menu %}

{% endblock %}

{% block content %}
 <form action="" method="post">
     {{ form }}
     {% csrf_token %}
     <input type="submit" value="Save">
 </form>

{% endblock %}

post/templates/post/post_page.html
{% extends "core/base.html" %}

{% block title %}

<h1>Страница поста {{post.pk}}</h1>

{% endblock %}

{% block menu %}

{% endblock %}

{% block content %}

<h2>{{ post.title }}</h2>

<h3> by {{ post.author }}</h3>

<h3> Относится к категориям </h3>

{% for category in post.categories.all%}

<h3><div><a href="{% url "categories:current_category" pk=category.pk %}">{{ category.title }}</a></div></h3>

{% endfor %}

<h3><div><a href="{% url "posts:post_update" pk=category.pk %}">Редактировать пост</a></div></h3>


<h3> Комментарии </h3>
{% for comment in post.comments.all%}

   <div>{{ comment.text }}</div>

    {% endfor %}

<h3> Оставьте комментарий </h3>
 <form action="" method="post">
     {{ form }}
     {% csrf_token %}
     <input type="submit" value="Save">
 </form>


{% endblock %}