application/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from core.views import Main_page, RegisterFormView
from django.contrib.auth.views import LoginView
from django.conf import settings
from django.contrib.auth.views import logout


urlpatterns = [

    url(r'^register/$', RegisterFormView.as_view()),
    url(r'^login/$', LoginView.as_view(template_name = 'core/login.html'),name = 'login'),
    url(r'^logout/$', logout, {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),
    url(r'^$', Main_page.as_view(),name = 'main'),
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blogs')),
    url(r'^post/', include('post.urls', namespace='posts')),
    url(r'^category/', include('category.urls', namespace='categories')),
]

blog/urls.py
from django.conf.urls import url
from blog.views import *

urlpatterns = [

    url(r'^$', Blog_list.as_view(), name="blogview"),
    url(r'^(?P<pk>\d+)/$', blog_page, name="currentblog"),

]

post/urls.py
from django.conf.urls import url
from .views import *

from django.contrib.auth.decorators import login_required


urlpatterns = [

    url(r'^(?P<pk>\d+)/$',Post_page.as_view(), name="currentpost"),
    url(r'^new/$',login_required(New_Post.as_view()), name="post_creation"),
    url(r'^(?P<pk>\d+)/edit/$',login_required(Post_Update.as_view()), name="post_update"),
]

blog/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.conf import settings





class Blog(models.Model):

    author = models.ForeignKey(settings.AUTH_USER_MODEL)
    title = models.CharField(max_length=255,verbose_name=u'Title')
    text = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_deleted = models.BooleanField(default=False)

    def __unicode__(self):
        return self.title

# Create your models here.

blog/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from .models import Blog
from django.views.generic import ListView
from django.shortcuts import render,get_object_or_404

class Blog_list(ListView):

    model = Blog
    context_object_name = 'blogs'
    template_name = "blog/blog_list.html"

#class Blog_page(ListView):

    #model = Blog
    #context_object_name = 'blog'
    #template_name = "blog/blog_page.html"

def blog_page(request, pk=None):
    blog = get_object_or_404(Blog.objects, pk=pk)
    return render(request, 'blog/blog_page.html', {'blog': blog})
# Create your views here.

blog/templates/blog/blog_list.html
{% extends "core/base.html" %}

{% block title %}
<h1>Список блогов</h1>
{% endblock %}

{% block menu %}

{% endblock %}

{% block content %}

  {% for blog in blogs %}

       <div><a href="{% url "blogs:currentblog" pk=blog.pk %}">{{ blog.title }}</a></div>

    {% endfor %}

{% endblock %}

blog/templates/blog/blog_page.html
{% extends "core/base.html" %}

{% block title %}
    Страница постов блога {{ blog.id }}
{% endblock %}

{% block menu %}

{% endblock %}

{% block content %}

    {% for post in blog.posts.all%}

         <div><a href="{% url "posts:currentpost" pk=post.pk %}">{{ post.title }}</a></div>

    {% endfor %}

{% endblock%}