application/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from core.views import Main_page, RegisterFormView
from django.contrib.auth.views import LoginView
from django.conf import settings
from django.contrib.auth.views import logout


urlpatterns = [

    url(r'^register/$', RegisterFormView.as_view()),
    url(r'^login/$', LoginView.as_view(template_name = 'core/login.html'),name = 'login'),
    url(r'^logout/$', logout, {'next_page': settings.LOGOUT_REDIRECT_URL}, name='logout'),
    url(r'^$', Main_page.as_view(),name = 'main'),
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog.urls', namespace='blogs')),
    url(r'^post/', include('post.urls', namespace='posts')),
    url(r'^category/', include('category.urls', namespace='categories')),
]

blog/urls.py
from django.conf.urls import url
from blog.views import *

urlpatterns = [

    url(r'^$', Blog_list.as_view(), name="blogview"),
    url(r'^(?P<pk>\d+)/$', blog_page, name="currentblog"),

]

category/urls.py
from django.conf.urls import url
from .views import *


urlpatterns = [

    url(r'^$', Category_list.as_view(), name="category_list"),
    url(r'^(?P<pk>\d+)/$', Category_page, name="current_category"),

]

core/urls.py
from django.conf.urls import url
from core.views import  Main_page

urlpatterns = [
    url(r'^$', Main_page.as_view()),
]

post/urls.py
from django.conf.urls import url
from .views import *

from django.contrib.auth.decorators import login_required


urlpatterns = [

    url(r'^(?P<pk>\d+)/$',Post_page.as_view(), name="currentpost"),
    url(r'^new/$',login_required(New_Post.as_view()), name="post_creation"),
    url(r'^(?P<pk>\d+)/edit/$',login_required(Post_Update.as_view()), name="post_update"),
]

core/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):

    pass



# Create your models here.

core/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.views.generic import ListView
from django.views.generic.edit import FormView
from post.models import Category, Post
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm as BaseUserCreationForm
from django.shortcuts import render,reverse,redirect


class UserCreationForm(BaseUserCreationForm):

    class Meta:
        model = get_user_model()
        fields = ("username", "email", "password1", "password2")



class RegisterFormView(FormView):

    form_class = UserCreationForm
    success_url = "login"
    template_name = "core/register.html"

    def form_valid(self, form):
        form.save()
        return super(RegisterFormView, self).form_valid(form)

    def get_success_url(self):
        return reverse('main')


class Main_page(ListView):
        model = Category
        context_object_name = 'categories'
        template_name = "core/base.html"

core/templates/core/base.html
{% block title %}
  <h1>This is my site</h1>
{% endblock %}

{% block menu %}
<h2>This is main menu</h2>
{% endblock %}



{% block content %}

<div><a href="{% url "categories:category_list"  %}">Список категорий</a></div>

  <div><a href="{% url "blogs:blogview"  %}">Список блогов</a></div>

  <div><a href="{% url "posts:post_creation"  %}">Создать пост</a></div>

    <div><a href="{% url "logout"  %}">Сменить аккаунт</a></div>


{% endblock %}



<footer>
    copyright
</footer>

core/templates/core/login.html
{% extends "core/base.html" %}


{% block menu %}

{% endblock %}

{% block content %}
 <form action="" method="post">
     {% csrf_token %}
     {{ form }}
     <input type="submit" value="Login">
 </form>

{% endblock %}

core/templates/core/register.html
<html>
  <head>
    <title>Регистрация</title>
  </head>
  <body>
    <form action="" method="post">
      {% csrf_token %}
      <!-- as_p для того, чтобы каждый элемент формы был с новой строки -->
      {{ form.as_p }}
      <button type="submit">Зарегистрироваться</button>
    </form>
  </body>
</html>